# Generated by Django 6.0.4 on 2026-07-21 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('tel', models.TextField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('working_hours', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('type', models.CharField(choices=[('business', 'Business'), ('customer', 'Customer')], default='customer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
