# Generated by Django 6.0.4 on 2026-07-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('tel', models.TextField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('working_hours', models.FloatField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
