# Generated by Django 6.0.4 on 2026-07-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileModel',
        ),
    ]
